### PR TITLE
Optimization framework redesign using Arena

### PR DESCRIPTION
**Pull request by Dandandan**
This the redesign of the optimizer using Arena in. the optimizer.
 
Benefit is that cloning / copying is cheap and allocations need to be done after "loading" and some other performance benefits as well.

### CODE REVIEW

**Comment by Dandandan** [comment]
@ritchie46 

Passes tests now, will do some more work & refactoring but this shows the concept.

* Tree is stored in arena. Makes it efficient to iterate and mutate the tree without any cloning of sub trees / doing large allocations.
* Rules can not mutate data themselves but return replacement if any.
* Small algorithmic change: apply rule until it doesn't match. This will help when having a long chain of something like 1+(1+(1+(1+1)) . which otherwise would need multiple iterations. Could later be even made a bit smarter to cover multiple rules instead.

**Comment by ritchie46** [comment]
@Dandandan Looks good. The Arena is somehting we probably could use in more places, so could you move it somewhere in the root of the polars directory?

And there is a blob of uncommented code. Could you remove that?

**Comment by Dandandan** [comment]
> @Dandandan Looks good. The Arena is somehting we probably could use in more places, so could you move it somewhere in the root of the polars directory?

Yes both.

> And there is a blob of uncommented code. Could you remove that?

Yes will do. Also some remaining refactoring to be done.

**Comment by Dandandan** [comment]
@ritchie46 for me PR is in OK state now.

**Comment by ritchie46** [comment]
Nice work! 

Only the linter isn't very happy yet.

**Comment by Dandandan** [comment]
Ah, thanks. Should be fixed now  :)

**Pull request merged**
