### PR TITLE
change infer schema and import csv

### PR DESCRIPTION
**Pull request by qtablesheets**
change infer schema and import for csv with
* floats in scientific notation
* spaces to trim
* missing values, sparse columns
add test_import_csv

### CODE REVIEW

**Comment by ritchie46** [comment]
Hi.. Could you take a look at your formatted and clippy hints. The ci pipeline is failing on those. 

Could you explain to me why you want the csv parser changed? As you propose you modify an empty string as being a `Null` type. Which in Polars/ Arrow is something different than an empty string. If you want empty strings to be `Null`, you can always set them to `null` afterwards.

**Comment by qtablesheets** [comment]
Hi, thanks for checking. 
I have tried to read real world csv with sparse float columns in scientific notation, which were infered as Int64 or UTF8, if there were missing values. Setting the empty string as Null type in the code is only used to remove it later before the possibilities are matched.
May be I am missing something here, because I am not immersed in polars/arrow at all, only testing it for clean/filter/accumulate those csv files. 
I will have a look at frmt and lint issues, it is my first PR ever, therefore I am still learning.

**Comment by ritchie46** [comment]
>  have tried to read real world csv with sparse float columns in scientific notation, which were infered as Int64 or UTF8, if there were missing values. Setting the empty string as Null type in the code is only used to remove it later before the possibilities are matched. 
You could use [str_lengths method](https://github.com/ritchie46/polars/blob/af5034cdf79b70e8bb942c9433586956dd45cbe6/polars/src/chunked_array/strings.rs#L31) to later replace the empty string values with something you see fit. 

I haven't got any benchmarks in place yet. But it is important that current csv parser is very fast, more important than supporting exotic types. Therefore I don't want to pay the overhead of doing utf8 validation during parsing. Once the benchmarks are in place we can take a loot at adding features that don't regress performance.

**Comment by qtablesheets** [comment]
Thanks again for commenting.
Meanwhile I have fixed the fmt/issues, but I will keep the changes local then. 
Please tell, if I should push that commit nevertheless. 

The real world files only have float columns in scientific notation with missing values, i.e. are looking quite standard.
The small test_import_csv file contains additional spaces, which may be inserted by user editing in rare cases.

A simple benchmark with one file: 
shape: (156, 2754)
time: 2.547457s
It is fast enough my purposes, but may be too slow for others.

**Comment by qtablesheets** [comment]
For completeness, please find the file attached, where polars 0.9.0 panics during import.
[test_import.zip](https://github.com/ritchie46/polars/files/5648739/test_import.zip)

**Comment by ritchie46** [comment]
> For completeness, please find the file attached, where polars 0.9.0 panics during import.
test_import.zip

I will take a look and see if we can add support for those.

**Pull request closed without merging**
