### PR TITLE
Use arrow 3.0.0 release

### PR DESCRIPTION
**Pull request by ritchie46**

### CODE REVIEW

**Comment by alippai** [comment]
Did the performance improve directly from this PR?

**Comment by ritchie46** [comment]
I haven't set up proper benchmarks yet, so that is hard to say. However, for `master` I don't think so because it already used an arrow versions of not more than a few weeks old (using github dependencies).

Latest weeks Polars has seen substantial performance increases in grouping/ hash joins and csv parsing.

**Comment by alippai** [comment]
Somehow I thought that you are on 2.0
Also the threadpool usage sounds interesting too :)

Thanks!

**Comment by ritchie46** [comment]
Yes.. The release on crates.io is on Arrow 2.0 indeed. I have however decided to stay in lockstep behind the developments on `master`. This will smear out the pain of backwards incompatible changes for me.

**Pull request merged**
